### ISSUE TITLE
spec_helper.rb - confused with search locations.

### ISSUE THREAD

**Issue by kireevco** [neillturner/kitchen-verifier-serverspec#24]
I'm trying to get `remote_exec: false` mode to get working. I am using username/empty password login, so I had to modify `spec_helper.rb`. But I don't think spec files are picking it up correctly. 

I'm probably doing something  wrong. I would appreciate any kind of help.
I'm usingMacOS X.

I'm getting test failures for each test. like that:

```
File "/test-file1"
  should be file (FAILED - 1)

Failures:

  1) File "/test-file1" should be file
     On host `127.0.0.1'
     Failure/Error: it { should be_file }
       expected `File "/test-file1".file?` to return true, got false
       /bin/sh -c test\ -f\ /test-file1

     # ./test/integration/default/serverspec/touchtest_spec.rb:7:in `block (2 levels) in <top (required)>'
```

```
tree .
.
└── integration
    └── default
        └── serverspec
            ├── spec_helper.rb
            ├── ssh_spec.rb
            └── touchtest_spec.rb
```

```
# touchtest_spec.rb
require_relative 'spec_helper'
require 'serverspec'
set :backend, :exec
set :os, :family => 'linux'

describe file('/test-file1') do
  it { should be_file }
end
```

```
# spec_helper.rb
require 'rubygems'
require 'bundler/setup'

require 'serverspec'
require 'pathname'
require 'net/ssh'



RSpec.configure do |config|
  set :host, '127.0.0.1'
  # ssh options at http://net-ssh.github.io/net-ssh/Net/SSH.html#method-c-start
  # ssh via ssh key (only)
  set :ssh_options,
      :user => 'root',
      :password => '',
      :port => '2222',
      # :auth_methods => [ 'publickey', 'password' ],
      :paranoid => false,
      :verbose => :debug
  set :backend, :ssh
  set :request_pty, true
end
```

```
# ../kitchen.yml
---
driver:
  name: vagrant
  ssh:
    insert_key: false
    shell: '"/bin/sh"'

  # Ensure no synced directores are needed for caching
  disable_cache: true
  cache_directory:

  customize:
    cableconnected1: 'on'

verifier:
  name: serverspec
  remote_exec: false
  bundler_path: '/usr/local/bin'
  rspec_path: '/usr/local/bin'
  gemfile: Gemfile
  default_pattern: true

suites:
  - name: default
```
