### ISSUE TITLE
kitchen verify finishes with 0 examples, 0 failures for serverspec tests while testing ansible role with docker as driver

### ISSUE THREAD

**Issue by westmurthy** [neillturner/kitchen-verifier-serverspec#27]
I am working to test ansible playbook or roles with test-kitchen using kitchen-ansible,serverspec for testing of playbooks with docker driver  on a  redhat 6.6 server( workstation). I can able to run kitchen convergence successfully.While running kitchen verify, it was unable to find my test cases and returning the below response. i am not sure why it is not picking up my test cases and running.
I have playbook default.yml and it calls the role splunk and the main.yml in splunk role will create the directory called splunk in /opt folder of the test server. and the test_spec.rb will check if it is directory or not.

Kitchen converge is running the playbook and created the splunk folder in the docker container.
while running kitchen verify below output is coming saying it doesn't find the examples. 
I am quite sure, I might be missing something related to verifier and suites section in .kitchen.yml. Was trying to fix for couple of days and no luck. can you help me out.

found similar issue https://github.com/neillturner/kitchen-ansible/issues/135  but with older ansible spec plugin.

```
**_Installing serverspec 2.38.0
       Bundle complete! 2 Gemfile dependencies, 15 gems now installed.
       Use `bundle show [gemname]` to see where a bundled gem is installed.
       Transferring files to <ansible-ubuntu-1404>
       Running Serverspec
       Using default pattern /tmp/verifier/suites/serverspec/*_spec.rb
       ---> RSPEC_CMD variable is: /usr/local/bin/rspec
       No examples found.

       Finished in 0.00032 seconds (files took 0.04711 seconds to load)
       0 examples, 0 failures

       Finished verifying <ansible-ubuntu-1404> (0m14.21s)._**
```

 on the kitchen login, i can see my test files test_spec.rb file existing.

kitchen@f5171c3a7133:/tmp/verifier/serverspec$ ll
total 16
drwxr-xr-x 2 kitchen kitchen 4096 Mar 31 19:56 ./
drwxr-xr-x 3 kitchen kitchen 4096 Mar 31 19:56 ../
-rwxr-xr-x 1 kitchen kitchen   41 Mar 31 19:56 spec_helper.rb*
-rwxr-xr-x 1 kitchen kitchen  162 Mar 31 19:56 test_spec.rb*

**My project structure:**
/opt/ansible/ansible-kitchen - folder

│ default.yml
│ .kitchen
│ .kitchen.yml
│ Gemfile
│ Gemfile.lock
├── roles
│   └── splunk
│       ├── defaults
│       ├── files
│       ├── handlers
│       ├── meta
│       ├── spec
│       ├── tasks
│            └── main.yml
│       ├── templates
│       ├── tests
│       └── vars
├── spec
│    ──spec_helper.rb
├── test
│   └── integration
│         └── default
│         │    ├── serverspec
│         │      ├── spec_helper.rb
│         │      └── test_spec.rb
│          ── default.yml
│
│         
│
│     
└── vendor

**contents of .kitchen.yml**

```
---
driver:
  name: docker
  use_sudo: false

platforms:
  - name: ubuntu-14.04
    driver:
       image: rndmh3ro/docker-ubuntu1404-ansible:latest
       platform: ubuntu


provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  roles_path: roles
  ansible_verbose: false
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_chef_for_busser: false
  ansible_connection: ssh


verifier:
  name: serverspec
  use_sudo: yes
  sudo_path: true

suites:
  - name: default
    verifier:
        default_pattern: true
        bundler_path: '/usr/local/bin'
        rspec_path: '/usr/local/bin'
        env_vars:
              TARGET_HOST: 127.0.0.1
              SUDO: true
```

**Contents of Gem file**

```
source 'https://rubygems.org'
gem 'test-kitchen', '~> 1.8.0'
gem 'kitchen-docker'
gem 'kitchen-ansible'
gem 'net-ssh'
gem 'serverspec'
gem 'kitchen-verifier-serverspec'

```

**contents of default.yml**

```
---
- hosts: test-kitchen

  roles:
     - splunk
```

**contents of  /roles/splunk/tasks/main.yml** 
```
---
 - name: create directory
   file: path=/opt/splunk state=directory
```

**contents of spec_helper.rb**
```

require 'serverspec'
set :backend, :exec
```

**contents of test_spec.rb** 

```
#require 'spec_helper'
#set :backend, :exec
require '/tmp/kitchen/spec/spec_helper.rb'

describe file ('/opt/splunk') do
        it { should be_a_directory 
end
```
