### ISSUE TITLE
'kitchen verify' finds no tests on 1st run, but finds them on 2nd run

### ISSUE THREAD

**Issue by themasterchef** [neillturner/kitchen-verifier-serverspec#29]
## Description

If I run 'kitchen verify' to run my integration tests, the 1st time it cannot find any tests to run, but the 2nd time I run 'kitchen verify' it finds all the tests.

I have had a cursory look round the gem but the only hunch I can come up with is that the default pattern expects to find tests in /tmp/verifier/suites/serverspec/blah_spec.rb, but sometimes after the first run this doesn't exist - /tmp/verifier/serverspec/blah_spec.rb exists instead.

## Setup

* macOS Sierra
* ruby 2.3.3p222
* kitchen-verifier-serverspec 0.6.8
* test-kitchen 1.16.0
* kitchen-docker 2.6.0
* Amazon Linux Docker image 2016.09

## Verifier options

Some of this is to make up for a separate bug when Amazon Linux is used with the verifier.

* name: serverspec
* ruby_bindir: /usr/bin
* default_pattern: true
* additional_install_command: sudo -E -H yum install -y ruby-devel gcc gcc-c++ make; sudo gem install up-console

**Comment by hurricanehrndz** [comment]
I can confirm the issue.

**Comment by neillturner** [comment]
do you have a kitchen.yml file i can use to reproduce with vagrant

**Comment by themasterchef** [comment]
Here is the .kitchen.yml file.

```
driver:
  name: docker
  use_sudo: false
  provision_command: yum -y install puppet3

platforms:
- name: amazonlinux
  driver_config:
    image: amazonlinux:2016.09
    platform: rhel

provisioner:
  name: puppet_apply
  require_puppet_repo: false
  require_puppet_collections: false
  require_puppet_omnibus: false
  require_chef_for_busser: false
  manifests_path: test/integration
  files_path: files
  manifest: default/init.pp
  puppet_environment: blah

suites:
- name: default
- name: foo

verifier:
  name: serverspec
  ruby_bindir: /usr/bin
  default_pattern: true
  additional_install_command: sudo -E -H yum -y install ruby-devel gcc gcc-c++ make; sudo gem install io-console
```
