### ISSUE TITLE
CentOS 6.x failure

### ISSUE THREAD

**Issue by pmyjavec** [neillturner/kitchen-verifier-serverspec#31]
When testing against CentOS 6 hosts, it seems the `rubygems` package is not installed which then causes the "verify" step to fail.

To resolve the issue I just logged into the box manually and installed `rubygems`

See the output:

```
>>>>>> ------Exception-------                                                        
>>>>>> Class: Kitchen::ActionFailed                                                  
>>>>>> Message: 1 actions failed.                                                    
>>>>>>     Failed to complete #verify action: [SSH exited (1) for command: [                                                                                               
            if [ ! $(which ruby) ]; then                                             
              echo '-----> Installing ruby, will try to determine platform os'       
              if [ -f /etc/centos-release ] || [ -f /etc/redhat-release ] || [ -f /etc/oracle-release ]; then                                                              
                sudo -E -H yum -y install ruby                                       
              else                                                                   
                if [ -f /etc/system-release ] && grep -q 'Amazon Linux' /etc/system-release; then                                                                          
                  sudo -E -H yum -y install ruby                                     
                else                                                                 
                  sudo -E -H apt-get -y install ruby                                 
                fi                                                                   
              fi                                                                     
            fi                                                                       
                        if [ "$(sudo -E -H gem list bundler -i)" = "true" ]; then    
              echo "Bundler already installed"                                       
            else                                                                     
              if [ "$(sudo -E -H gem list bundler -i)" = "false" ]; then             
                sudo -E -H gem install  --no-ri --no-rdoc bundler                    
              else                                                                   
                echo "ERROR: Ruby not installed correctly"                           
                exit 1                                                               
              fi                                                                     
            fi                                                                       

            if [ -d /tmp/kitchen ]; then                                             
                            if [ "$(sudo -E -H gem list serverspec -i)" = "false" ]; then                                                                                  
                        sudo -E -H rm -f /tmp/kitchen/Gemfile                        
          sudo -E -H echo "source 'https://rubygems.org'" >> /tmp/kitchen/Gemfile    
          sudo -E -H echo "gem 'net-ssh','~> 2.9'"  >> /tmp/kitchen/Gemfile          
          sudo -E -H echo "gem 'serverspec'" >> /tmp/kitchen/Gemfile                 

              BUNDLE_CMD=$(which bundle)                                             
              echo "---> BUNDLE_CMD variable is: ${BUNDLE_CMD}"                      
              sudo -E -H  $BUNDLE_CMD install --gemfile=/tmp/kitchen/Gemfile         
            fi                                                                       

                                                                                     
            else                                                                     
              echo "ERROR: Default path '/tmp/kitchen' does not exist"               
              exit 1                                                                 
            fi                                                                       
]] on default-centos-6                                                               
>>>>>> ----------------------                                                        
>>>>>> Please see .kitchen/logs/kitchen.log for more details                         
>>>>>> Also try running `kitchen diagnose --all` for configuration                   
```

```
---
# kitchen.yml
driver:
  name: 'vagrant'

provisioner:
  name: 'ansible_playbook'
  hosts: "localhost"
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_ansible_source: false
  require_pip: true
  ansible_version: 'latest'
  ansible_verbose: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ignore_paths_from_root: [".git",".idea",".kitchen", ".bin", ".kitchen.yml", ".gems", ".bundle"]

verifier:
  name: 'serverspec'
  default_pattern: true

platforms:
  - name: 'ubuntu-16.04'
  - name: 'centos-7'
  - name: 'centos-6'

suites:
  - name: 'default'
    attributes:
    run_list:
```
