### ISSUE TITLE
Overwriting Gemfile when setting remote_exec false 

### ISSUE THREAD

**Issue by alexharv074** [neillturner/kitchen-verifier-serverspec#7]
Given the following `.kitchen.yml`:

``` yaml

---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false

verifier:
  name: serverspec
  remote_exec: false
  bundler_path: '/usr/local/bin'
  rspec_path: '/usr/local/bin'
  patterns:
    - test/integration/default/serverspec/default_spec.rb

platforms:
  - name: centos-7.2

suites:
  - name: default
```

looks like the code [here](https://github.com/neillturner/kitchen-verifier-serverspec/blob/master/lib/kitchen/verifier/serverspec.rb#L204-L209) is overwriting my project's Gemfile, which I'd have to assume is a bug.
