### ISSUE TITLE
Must env_vars be hardcoded into .kitchen.yml?

### ISSUE THREAD

**Issue by j4m3s** [neillturner/kitchen-verifier-serverspec#8]
I'm using option 3: 'Locally on your workstation running serverspec in ssh mode'

At the start of a 'kitchen verify' run, test-kitchen knows the details of the instance it is testing, and outputs them to the terminal, e.g. 
```
[Serverspec] Verify on instance=#<Kitchen::Instance:0x0000000280a2f8> with state={:hostname=>"127.0.0.1", :port=>"2222", :username=>"vagrant", :ssh_key=>
```
Can those connection details not be automatically be picked-up and used for the test suite, rather than having to hard-code them into the .kitchen.yml file as described in the README?:
```yaml
      env_vars:
        TARGET_HOST: 127.0.0.1
        TARGET_PORT: 2222
        LOGIN_USER: vagrant
        SSH_KEY: 'c:/repository/puppet_repo/private_key.pem'
```
